_BASE_: "../Pascal/base.yaml"
MODEL:
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 80
    NAME: "ScoreOutputROIHeads"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
